export const BOOK_DETAIL_STATE = 'book';

export const BOOK_DETAIL_REQUEST = 'BOOK_DETAIL_REQUEST';
export const BOOK_DETAIL_SUCCESS = 'BOOK_DETAIL_SUCCESS';
export const BOOK_DETAIL_FAILURE = 'BOOK_DETAIL_FAILURE';
