export const CHARACTERS_STATE = 'characters';
export const CHARACTER_LIST_REQUEST = 'CHARACTER_LIST_REQUEST';
export const CHARACTER_LIST_SUCCESS = 'CHARACTER_LIST_SUCCESS';
export const CHARACTER_LIST_FAILURE = 'CHARACTER_LIST_FAILURE';
